# Generated by Django 4.2.4 on 2023-08-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='postalcode',
        ),
        migrations.RemoveField(
            model_name='company',
            name='provincestate',
        ),
        migrations.RemoveField(
            model_name='company',
            name='town',
        ),
    ]
